# -*- coding: utf-8 -*-
import os
import sys
import shutil
import numpy as np
import cv2
from tqdm import tqdm

# Dynamically add libs path
PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
NCD_PATH = os.path.join(PROJECT_ROOT, 'libs', 'AnomalyNCD')
sys.path.append(NCD_PATH)

# ==========================================
# Data Bridge
# ==========================================
# Purpose: Convert .npy heatmaps generated by MuSc into a format readable by AnomalyNCD.
#
# AnomalyNCD's binarization() function requires (using MTD/custom-style layout):
#
#   dataset_path/                  <- origin_image_path (args.dataset_path)
#     <anomaly_type>/              <- e.g. "unknown"
#       img001.png
#
#   anomaly_map_path/              <- args.anomaly_map_path
#     <category>/                  <- e.g. "unknown"
#       <anomaly_type>/            <- e.g. "unknown"
#         img001.png               <- PNG grayscale, NOT .npy
#
# AnomalyNCD then creates (via MEBin):
#   binary_data_path/<category>/   <- binary masks (created by AnomalyNCD itself)
#   crop_data_path/<category>/     <- cropped ROIs (created by AnomalyNCD itself)
#     images/<anomaly_type>/
#     masks/<anomaly_type>/
#
# The DataBridge is responsible ONLY for steps 1-2 above.
# It must NOT pre-create binary masks ¡ª that is MEBin's job.

CATEGORY_NAME = "unknown"    # must match AnomalyNCDWrapper's category arg
ANOMALY_TYPE  = "unknown"    # single anomaly-type bucket for all our unlabelled images

class DataBridge:
    def __init__(self):
        pass

    def prepare_ncd_dataset(self, raw_images_dir, maps_dir, output_base_dir):
        """
        Convert MuSc outputs into the directory layout that AnomalyNCD.binarization()
        expects when dataset='custom' (same as 'mtd').

        Args:
            raw_images_dir (str): Folder containing original input images.
            maps_dir (str):       Folder containing .npy anomaly maps from MuSc
                                  (files named  <basename>_map.npy).
            output_base_dir (str): Root output folder.  Two sub-trees are created here.

        Returns:
            dict with keys:
                'images_path'      -> dataset_path to pass to AnomalyNCD  (custom layout)
                'anomaly_maps_path'-> anomaly_map_path to pass to AnomalyNCD
            or None on failure.
        """
        print(f"[DataBridge] Starting data preparation for AnomalyNCD...")

        # 1. Build destination directories
        #    custom layout: dataset_path/<anomaly_type>/img.png
        images_root     = os.path.join(output_base_dir, "images")
        out_images_dir  = os.path.join(images_root, ANOMALY_TYPE)

        #    Map layout:  anomaly_map_path/<category>/<anomaly_type>/img.png
        maps_root       = os.path.join(output_base_dir, "anomaly_maps")
        out_maps_dir    = os.path.join(maps_root, CATEGORY_NAME, ANOMALY_TYPE)

        for d in [out_images_dir, out_maps_dir]:
            os.makedirs(d, exist_ok=True)

        # 2. Iterate original images and their matching .npy maps
        valid_exts = ('.png', '.jpg', '.jpeg', '.bmp', '.tiff')
        image_files = sorted(
            f for f in os.listdir(raw_images_dir) if f.lower().endswith(valid_exts)
        )

        if not image_files:
            print(f"[DataBridge] Error: No images found in {raw_images_dir}")
            return None

        processed_count = 0

        for img_name in tqdm(image_files, desc="Bridging Data"):
            base_name = os.path.splitext(img_name)[0]
            img_path  = os.path.join(raw_images_dir, img_name)
            map_path  = os.path.join(maps_dir, f"{base_name}_map.npy")

            if not os.path.exists(map_path):
                print(f"[DataBridge] Warning: Map not found for {img_name}, skipping.")
                continue

            # 3. Copy original image (unchanged) into custom images layout
            dest_img_path = os.path.join(out_images_dir, img_name)
            shutil.copy2(img_path, dest_img_path)

            # 4. Convert .npy anomaly map ¡ú 8-bit grayscale PNG
            #    AnomalyNCD's MEBin reads PNG via cv2.imread(x, cv2.IMREAD_GRAYSCALE)
            anomaly_map = np.load(map_path)
            map_min, map_max = float(anomaly_map.min()), float(anomaly_map.max())
            if map_max > map_min:
                norm_map = (anomaly_map - map_min) / (map_max - map_min)
            else:
                norm_map = np.zeros_like(anomaly_map)
            map_uint8 = (norm_map * 255).astype(np.uint8)

            dest_map_path = os.path.join(out_maps_dir, f"{base_name}.png")
            cv2.imwrite(dest_map_path, map_uint8)

            processed_count += 1

        print(f"[DataBridge] Prepared {processed_count} image-map pairs.")
        print(f"[DataBridge]   images_path      -> {images_root}")
        print(f"[DataBridge]   anomaly_maps_path-> {maps_root}")

        return {
            'images_path':       images_root,
            'anomaly_maps_path': maps_root,
        }


# ==========================================
# Simple test code
# ==========================================
if __name__ == "__main__":
    bridge = DataBridge()

    raw_dir  = os.path.join(PROJECT_ROOT, 'data_store', 'raw_inputs')
    maps_dir = os.path.join(PROJECT_ROOT, 'data_store', 'intermediate', 'maps')
    out_dir  = os.path.join(PROJECT_ROOT, 'data_store', 'intermediate', 'ncd_data')

    # result = bridge.prepare_ncd_dataset(raw_dir, maps_dir, out_dir)
    # print(result)
