# -*- coding: utf-8 -*-
import os
import sys
import shutil
import numpy as np
import cv2
from tqdm import tqdm

# Dynamically add libs path
PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
NCD_PATH = os.path.join(PROJECT_ROOT, 'libs', 'AnomalyNCD')
sys.path.append(NCD_PATH)

# ==========================================
# Data Bridge
# ==========================================
# Purpose: Convert .npy heatmaps generated by MuSc into a format readable by AnomalyNCD.
# AnomalyNCD's MEBin module requires:
# 1. Original Image
# 2. Binary Mask - segmented from heatmap via threshold
# 3. Crop Image - anomaly region cropped based on mask
class DataBridge:
    def __init__(self, anomaly_thred=0.5, erode_iter=1):
        """
        Args:
            anomaly_thred (float): Threshold for heatmap binarization (0~1, or adjusted based on MuSc output range).
                                   Regions above this value are considered anomalies.
            erode_iter (int): Number of iterations for morphological erosion to remove noise.
        """
        self.anomaly_thred = anomaly_thred
        self.erode_iter = erode_iter
        
    def prepare_ncd_dataset(self, raw_images_dir, maps_dir, output_base_dir):
        """
        Core function: Read original images and heatmaps, generate directory structure required by AnomalyNCD.
        
        Args:
            raw_images_dir (str): Original images folder (e.g., data_store/raw_inputs)
            maps_dir (str): Folder with .npy heatmaps generated by MuSc (e.g., data_store/intermediate/maps)
            output_base_dir (str): Root directory for AnomalyNCD dataset (e.g., data_store/intermediate/ncd_data)
        """
        print(f"[DataBridge] Starting data preparation for AnomalyNCD...")
        
        # 1. Create directory structure required by AnomalyNCD
        # Assume we classify this batch of unknown images into a category named "unknown_batch"
        category_name = "unknown_batch"
        
        # AnomalyNCD usually requires 'images' and 'masks' subfolders
        out_images_dir = os.path.join(output_base_dir, category_name, "images")
        out_masks_dir = os.path.join(output_base_dir, category_name, "masks")
        
        os.makedirs(out_images_dir, exist_ok=True)
        os.makedirs(out_masks_dir, exist_ok=True)
        
        # 2. Iterate through original images to find corresponding heatmaps
        valid_exts = ('.png', '.jpg', '.jpeg', '.bmp', '.tiff')
        image_files = [f for f in os.listdir(raw_images_dir) if f.lower().endswith(valid_exts)]
        
        if not image_files:
            print(f"[DataBridge] Error: No images found in {raw_images_dir}")
            return None
            
        processed_count = 0
        
        for img_name in tqdm(image_files, desc="Bridging Data"):
            base_name = os.path.splitext(img_name)[0]
            img_path = os.path.join(raw_images_dir, img_name)
            map_path = os.path.join(maps_dir, f"{base_name}_map.npy")
            
            if not os.path.exists(map_path):
                print(f"[DataBridge] Warning: Map not found for {img_name}, skipping.")
                continue
                
            # 3. Read data
            # Read original image (to copy to target folder)
            image = cv2.imread(img_path)
            if image is None:
                continue
                
            # Read heatmap (float array)
            anomaly_map = np.load(map_path)
            
            # 4. Binarization
            # This is a prerequisite for AnomalyNCD MEBin module
            # Normalize float heatmap to 0-1 (if MuSc output is not 0-1)
            map_min, map_max = anomaly_map.min(), anomaly_map.max()
            if map_max > map_min:
                normalized_map = (anomaly_map - map_min) / (map_max - map_min)
            else:
                normalized_map = anomaly_map
                
            # Apply threshold to generate binary mask (0 or 255)
            binary_mask = np.zeros_like(normalized_map, dtype=np.uint8)
            binary_mask[normalized_map > self.anomaly_thred] = 255
            
            # Morphological operations: Erosion (remove isolated noise) and Dilation (connect broken regions)
            kernel = np.ones((3, 3), np.uint8)
            if self.erode_iter > 0:
                binary_mask = cv2.erode(binary_mask, kernel, iterations=self.erode_iter)
                binary_mask = cv2.dilate(binary_mask, kernel, iterations=self.erode_iter)
                
            # 5. Save to AnomalyNCD directory structure
            # Copy original image
            dest_img_path = os.path.join(out_images_dir, img_name)
            shutil.copy2(img_path, dest_img_path)
            
            # Save binarized mask (save as .png image, as AnomalyNCD Dataset usually reads images)
            # Note: AnomalyNCD might expect mask names to have a "_mask" suffix, depending on its dataset.py implementation
            # Here we save as same name first, modify later if it throws an error
            dest_mask_path = os.path.join(out_masks_dir, f"{base_name}.png")
            cv2.imwrite(dest_mask_path, binary_mask)
            
            processed_count += 1
            
        print(f"[DataBridge] Successfully prepared {processed_count} image-mask pairs.")
        print(f"[DataBridge] Dataset ready at: {output_base_dir}")
        
        # Return the constructed dataset root directory for the next stage
        return output_base_dir

# ==========================================
# Simple test code
# ==========================================
if __name__ == "__main__":
    bridge = DataBridge(anomaly_thred=0.6)
    
    raw_dir = os.path.join(PROJECT_ROOT, 'data_store', 'raw_inputs')
    maps_dir = os.path.join(PROJECT_ROOT, 'data_store', 'intermediate', 'maps')
    out_dir = os.path.join(PROJECT_ROOT, 'data_store', 'intermediate', 'ncd_data')
    
    # bridge.prepare_ncd_dataset(raw_dir, maps_dir, out_dir)
